services:
  - type: web
    name: discogs-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: discogs-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DISCOGS_TOKEN
        sync: false
      - key: DISCOGS_USERNAME
        sync: false
      - key: DISCOGS_FOLDER_ID
        sync: false

databases:
  - name: discogs-app-db
    databaseName: discogs_app_production
    user: discogs_app
