default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: discogs_app_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: discogs_app_test
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

  # Add these lines for Action Cable
  queue:
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    url: <%= ENV['DATABASE_URL'] %>
